Feature/project setup
Prangula/ImdbMovieApp pull request #1
Opened 2024-09-16 14:01 UTC by Prangula

2024-09-16 20:13 UTC, etozheluka commented on app/build.gradle.kts
> +    annotationProcessor("com.github.bumptech.glide:compiler:4.11.0")
i think you dont need glide compiler 
<img width="592" alt="image" src="https://github.com/user-attachments/assets/eb358d7b-6578-483c-9267-6cfe441018f4">

2024-09-16 20:15 UTC, ninikokra requested changes

2024-09-16 20:15 UTC, ninikokra commented on app/src/main/res/values/colors.xml
> +    <color name="neutralDarkestGrey">#1C1C1C</color>
please rename the colors as they are in Figma

2024-09-16 20:15 UTC, ninikokra commented on app/src/main/res/drawable/caution_logo.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
rename this with ic_caution
all icons should start with ic_name and all backgrounds should start with bkg_name

2024-09-16 20:15 UTC, ninikokra commented on app/src/main/res/drawable/imdb_logo.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
same here ic_logo_splash_screen or smthg like that

2024-09-16 20:15 UTC, ninikokra commented on app/src/main/res/drawable/no_results_logo.xml
> +    android:viewportWidth="106"
also here

2024-09-16 20:15 UTC, ninikokra commented on app/src/main/java/com/imdbmovieapp/ImdbMovieActivity.kt
> +class ImdbMovieActivity : AppCompatActivity() {
i dont like this name, you can try to simplify it with just MoviesActivity? imo its more readable

2024-09-17 09:30 UTC, ninikokra requested changes

2024-09-17 09:30 UTC, ninikokra commented on app/src/main/res/values/colors.xml
> +    <color name="neutral05LightGrey">#A5A5A5</color>
better to write neutral_04_Grey, neutral_05_light_grey it's more readable

2024-09-17 09:57 UTC, ninikokra approved these changes

2024-09-18 15:13 UTC, Davit-Tsiskarashvili approved these changes

2024-09-18 15:15 UTC, giorgimurgulia-space approved these changes

2024-09-18 15:17 UTC, merged