Feature/remote mappers repository use cases koin
Prangula/ImdbMovieApp pull request #5
Opened 2024-09-19 15:36 UTC by Prangula

created mappers,repositories and useCases for Remote Data.

2024-09-20 08:34 UTC, Davit-Tsiskarashvili requested changes

2024-09-20 08:34 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/remote/api/MoviesApi.kt
> +    suspend fun getDetailMovie(@Path("movie_id") movieId: String): Response<DetailMovieDto>
fun getMovieDetails() and MovieDetailsDto would be better names

2024-09-20 08:34 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/remote/mapper/domainToDto/GenreDomainToGenreDtoMapper.kt
> +        return with(model) {
just a suggestion, you don't need with(model) for just one parameter

2024-09-20 08:34 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/repository/ApiMovieRepositoryImpl.kt
> +class ApiMovieRepositoryImpl(
just MovieRepositoryImpl. You don't need Api as a prefix

2024-09-20 08:34 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/repository/ApiMovieRepositoryImpl.kt
> +        moviesApi.getPopularMovies().let { response ->
there is no point to have .let without ? before (I mean ?.let) and when moviesApi doesn't return nullable, you don't have to use .let

2024-09-20 08:34 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/remote/dto/genreMovieDto/GenreMovieDto.kt
> +data class GenreMovieDto(
Maybe MovieGenreDto was better, why did you change it?

2024-10-01 10:21 UTC, Davit-Tsiskarashvili requested changes

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/MovieApp.kt
> +                    databaseModule, mapperModule, repositoryModule, useCaseModule, retrofitModule,
for a better readability write each module on each line

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/local/database/FavoriteMovieDatabase.kt
> +    version = 2
Everytime you have crash on room version, you don't have to change version number. Just clear storage of app in your device and it will work fine

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/remote/mapper/DetailDtoToDomainMapper.kt
> +                        it.name
since you have parameter names everywhere else, it would be more beautiful to add here as well

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/remote/mapper/MovieGenreDtoToDomainMapper.kt
> +                        it.id,
here too

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/remote/mapper/PopularMoviesDtoToDomainMapper.kt
> +                        it.id,
add parameter names in every mapper

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/remote/network_utils/RetrofitHandler.kt
> +            Resource.Error(e.message ?: "No Internet Connection")
Just for the information. IOException is broader than just internet connectivity issue. Hence, a more general error message (like "network error") might be a better message

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/repository/MovieRepositoryImpl.kt
> +
remove empty line

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/data/repository/MovieRepositoryImpl.kt
> +) : ApiMovieRepository {
if the implementation name is "MovieRepositoryImpl", than interface should be called "MovieRepository" instead of "ApiMovieRepository"

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/di/MapperModule.kt
> +
empty line

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/di/RepositoryModule.kt
> +    single<FavoriteMovieRepository> { FavoriteMovieRepositoryImpl(get(), get(), get()) }
here you also can add parameter names to make more readable

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/base/BaseFragment.kt
> +
you can also write like this:

if (dialog != null) dialog!!.hide()

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/model/DetailMovieUI.kt
> +    val title: String,
extra comma on title

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/model/MoviesResultsUI.kt
> +
empty line

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/screen/activity_screen/MoviesActivity.kt
> +                }
write on one line

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/screen/home_movies_fragment/adapter/ResultsMoviesAdapter.kt
> +    (
move bracket on the 13th line

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/screen/home_movies_fragment/adapter/ResultsMoviesAdapter.kt
> +            genreMoviesUI: GenreMoviesUI,
remove comma

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/screen/home_movies_fragment/adapter/ResultsMoviesAdapter.kt
> +                if (item.getPosterUrl().isNotEmpty()) {
can getPosterUrl() ever be empty?

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/screen/home_movies_fragment/ui/HomeMoviesFragment.kt
> +            customSearchBar.showGenreTags(binding.homeGenresChipGroup)
remove binding

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/java/com/imdbmovieapp/presentation/screen/home_movies_fragment/ui/HomeMoviesFragment.kt
> +    private fun popularMoviesRecyclerView() {
rename into setupPopularMoviesRecyclerView or something similar

2024-10-01 10:21 UTC, Davit-Tsiskarashvili commented on app/src/main/res/drawable/bkg_rotate.xml
> +
empty line

2025-02-27 11:14 UTC, bchmsl approved these changes

2025-05-08 20:53 UTC, merged